#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Matrix elements of the electron-repulsion operator between two
n-electron wavefunctions Ψᵢ and Ψⱼ

   Cᵢⱼ = ∫dx1 ∫dx2...∫dxn Ψ*ᵢ(x1,x2,...,xn) ∑ᵦ<ᵧ 1/|rᵦ-rᵧ| Ψⱼ(x1,x2,...,xn)

with xᵦ=(rᵦ,σᵦ), are approximated a matrix functional of the matrix density,
i.e. C[D(r)].
"""
from abc import ABC, abstractmethod

try:
    import becke
except ImportError as err:
    print("""
    Solution of the Poisson equation requires the `becke` module
    which can be obtained from
       `https://github.com/humeniuka/becke_multicenter_integration`
    or can be installed from PyPI via
       pip install becke-multicenter-integration
    """)
    raise err

import numpy
import numpy.linalg as la

import pyscf.dft

from msdft.MultistateMatrixDensity import MultistateMatrixDensity


class HartreeLikeOperatorFunctional(object):
    def __init__(self, mol, level=8):
        """
        The Hartree energy is the interaction of a classical charge density with itself.
        There is no equivalent of the Hartree term in the multistate density functional
        formalism, because the Hartree part of the Coulomb energy does not correspond to
        an operator. We can define a functional of the matrix density D(r) that reduces
        to the Hartree energy in the case of a single electronic state, which is an
        analytical functional and transforms correctly under basis transformations U,
        i.e. `U⁻¹ J[D(r)] U = J[U⁻¹ D(r) U]` :

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫∫' Dᵢₖ(r) Dₖⱼ(r')/|r-r'|

        If there are multiple electronic state, the diagonals J[D(r)]ᵢᵢ differ from the
        classical Coulomb interaction of the state density of state i with itself, because
        the matrix product ∑ₖDᵢₖ(r) Dₖⱼ(r') mixes in transition densities to other
        states k≠i.

        :param mol: The molecule defines the integration grid.
        :type mol: pyscf.gto.Mole

        :param level: The level (3-8) controls the number of grid points
           in the integration grid.
        :type level: int
        """
        # generate a multicenter integration grid
        self.grids = pyscf.dft.gen_grid.Grids(mol)
        self.grids.level = level
        self.grids.build()

    def __call__(
            self,
            msmd : MultistateMatrixDensity):
        """
        compute the Hartree-like part of the electron-electron repulsion operator
        in the subspace of electronic states,

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫∫' Dᵢₖ(r) Dₖⱼ(r')/|r-r'|

        where Dᵢⱼ(r) is the electronic density of the state Ψᵢ, Dᵢᵢ(r) = ρᵢ(r),
        or the transition density between the states Ψᵢ and Ψⱼ, Dᵢⱼ(r).

        The 6-dimensional integral is calculated by solving the Poisson equation
        for the electrostatic potential generated by one of the (transition) densities,

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫ Dᵢₖ(r) Vₖⱼ(r)

        where

          ∇²Vₖⱼ(r) = -4π Dₖⱼ(r)

        is solved on a multicenter Becke grid.

        :param msmd: The multistate matrix density in the electronic subspace
        :type msmd: :class:`~.MultistateMatrixDensity`

        :return hartree_like_matrix: The Hartree-like matrix Jᵢⱼ in the subspace
           of the electronic states i,j=1,...,nstate
        :rtype hartree_like_matrix: numpy.ndarray of shape (nstate,nstate)
        """
        # number of grid points
        ncoord = self.grids.coords.shape[0]
        # number of electronic states in the subspace
        nstate = msmd.number_of_states

        # Evaluate D(r) on the integration grid.
        D, _, _ = msmd.evaluate(self.grids.coords)

        # For solving the Poisson equation another multicenter Becke grid
        # is employed, which can have a different number of angular and radial
        # grid points than the one for doing the integrals.

        # The multicenter grid is defined by the centers ...
        atomlist = []
        for nuclear_charge, nuclear_coords in zip(
                msmd.mol.atom_charges(), msmd.mol.atom_coords()):
            atomlist.append((int(nuclear_charge), nuclear_coords))
        # ... and the radial and angular grids.
        becke.settings.radial_grid_factor = 3
        becke.settings.lebedev_order = 23

        # [1] The Poisson equation is solved for each Dₖⱼ(r).
        V = numpy.zeros((nstate,nstate,ncoord))
        for k in range(0, nstate):
            for j in range(0, nstate):
                # A function for evaluating the (transition) density Dₖⱼ(r) on
                # the multicenter Becke grid.
                def density_function(x, y, z):
                    # The `becke` module and the `msdft` module use different
                    # shapes for the coordinates of the grid points. Before
                    # passing the grid to `msdft`, the arrays have to be flattened
                    # and reshaped as (ncoord,3). Before returning the density,
                    # it has to be brought into the same shape as each input coordinate
                    # array.
                    coords = numpy.vstack(
                        [x.flatten(), y.flatten(), z.flatten()]).transpose()

                    # Evaluate the density.
                    spin_density, _, _ = msmd.evaluate(coords)
                    # The Coulomb potential does not distinguish spins, so
                    # sum over spins.
                    density = spin_density[0,k,j,:]+ spin_density[1,k,j,:]

                    # Give it the same shape as the input arrays.
                    density = numpy.reshape(density, x.shape)
                    return density

                # The solution of the Poisson equation
                #  ∇²potential(r) = -4π density(r)
                # is returned as a callable.
                potential_function = becke.poisson(atomlist, density_function)

                # The electrostatic potential is evaluated on the same
                # integration grid as the density.
                V[k,j,:] = potential_function(
                    # x
                    self.grids.coords[:,0],
                    # y
                    self.grids.coords[:,1],
                    # z
                    self.grids.coords[:,2])

        # [2] Integrate and do the matrix-matrix product.
        #
        #  J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫ Dᵢₖ(r) Vₖⱼ(r)
        #
        hartree_like_matrix = 0.5 * numpy.einsum(
            'r,ikr,kjr->ij',
            self.grids.weights,
            # Both spins feel the same Coulomb potentials, so sum over spins.
            D[0,...]+D[1,...],
            V)

        return hartree_like_matrix


class ExchangeCorrelationLikeFunctional(ABC):
    def __init__(self, mol, level=8):
        """
        The abstract base class for multi-state exchange/correlation functionals.

        :param mol: The molecule defines the integration grid.
        :type mol: pyscf.gto.Mole

        :param level: The level (3-8) controls the number of grid points
           in the integration grid.
        :type level: int
        """
        # generate a multicenter integration grid
        self.grids = pyscf.dft.gen_grid.Grids(mol)
        self.grids.level = level
        self.grids.build()

    @abstractmethod
    def energy_density(
            self,
            msmd : MultistateMatrixDensity,
            coords : numpy.ndarray):
        pass

    def __call__(
            self,
            msmd : MultistateMatrixDensity,
            available_memory=1<<30):
        """
        compute the exchange/correlation-like contribution to the electron repulsion operator
        in the subspace of electronic states by evaluating the exchange/correlation energy
        functional XC[D(r)] on the matrix density D(r):

          XCᵢⱼ = XC[D(r)]ᵢⱼ = ∫ xc[D]ᵢⱼ(r) dr,

        where Dᵢⱼ(r) is the electronic density of the state Ψᵢ, Dᵢᵢ(r) = ρᵢ(r),
        or the transition density between the states Ψᵢ and Ψⱼ, Dᵢⱼ(r).
        xc[D](r) is a local approximation of the exchange/correlation energy density (XCED).

        :param msmd: The multistate matrix density in the electronic subspace
           for which the exchange energy functional should be evaluated.
        :type msmd: :class:`~.MultistateMatrixDensity`

        :param available_memory: The amount of memory (in bytes) that can be
           allocated for the exchange/correlation energy density. If more memory is needed,
           the XED is evaluated in multiple chunks. (1<<30 corresponds to 1Gb)
           Since more memory is needed for intermediate quantities, this limit
           is only a rough estimate.
        :type available_memory: int

        :return xc_like_matrix: The exchange/correlation energy matrix XCᵢⱼ in the subspace
           of the electronic states i,j=1,...,nstate
        :rtype xc_like_matrix: numpy.ndarray of shape (nstate,nstate)
        """
        # number of grid points
        ncoord = self.grids.coords.shape[0]
        # number of electronic states in the subspace
        nstate = msmd.number_of_states
        # matrix element of the exchange/correlation-like part of the electron repulsion operator.
        xc_like_matrix = numpy.zeros((nstate,nstate))

        # If the resulting array that holds the exchange/correlation energy density
        # exceeds `available_memory`, the XCED is evaluated on smaller chunks
        # of the grid and summed into the kinetic matrix at the end.
        needed_memory = 50 * 2 * xc_like_matrix.itemsize * nstate**2 * ncoord
        number_of_chunks = max(1, (needed_memory + available_memory) // available_memory)
        # There cannot be more chunks than grid points.
        number_of_chunks = min(ncoord, number_of_chunks)

        # Loop over chunks of grid points and associated integration weights.
        for coords, weights in zip(
                numpy.array_split(self.grids.coords, number_of_chunks),
                numpy.array_split(self.grids.weights, number_of_chunks)):

            # Evaluate the exchange/correlation energy density on the grid.
            XCED = self.energy_density(msmd, coords)

            # The matrix of the exchange/correlation-like part of the electron-repulsion
            # operator in the subspace is obtained by integration of XEDᵢⱼ(r) over space and spin
            #
            #   XCᵢⱼ = ∫ XCEDᵢⱼ(r) dr
            #
            xc_like_matrix += numpy.einsum('r,sijr->ij', weights, XCED)

        return xc_like_matrix


class LSDAExchangeLikeFunctional(ExchangeCorrelationLikeFunctional):
    # Cₓ = (3/4) (3/pi)¹ᐟ³ = 0.738 from Dirac's exchange-energy, Eqn. (6.1.20) in [Parr&Yang]
    Cx_Dirac = 0.7386
    # Cₓ from the "Gaussian" approximation in Eqn. (6.5.25) of [Parr&Yang]
    Cx_Gaussian = 0.7937

    def __init__(self, mol, level=8):
        """
        Multi-state exchange energy according to the local-spin density approximation
        (eqn. 8.2.16 in Ref. [Yang&Parr]),

        K[D(r)] = 2¹ᐟ³ Cₓ ∫ [ Dᵅ(r)⁴ᐟ³ + Dᵝ(r)⁴ᐟ³ ] dr

        D(r)⁴ᐟ³ is a fractional matrix-power of D(r), which is calculated by diagonalizing D.

        The value of the prefactor Cₓ = 0.7937 is taken from the "Gaussian" approximation in
        Eqn. (6.5.25) of chapter 6 in Ref. [Yang&Parr]

        References
        ----------
        [Yang&Parr] Parr & Yang (1989), "Density Functional Theory of Atoms and Molecules".

        :param mol: The molecule defines the integration grid.
        :type mol: pyscf.gto.Mole

        :param level: The level (3-8) controls the number of grid points
           in the integration grid.
        :type level: int
        """
        # generate a multicenter integration grid
        self.grids = pyscf.dft.gen_grid.Grids(mol)
        self.grids.level = level
        self.grids.build()

    def energy_density(
            self,
            msmd : MultistateMatrixDensity,
            coords : numpy.ndarray):
        """
        compute the energy density for the exchange-like part of the electron-electron
        repulsion operator in the subspace of electronic states,

          XED[D]ᵢⱼ(r) = 2¹ᐟ³ Cₓ [D(r)⁴ᐟ³]ᵢⱼ

        NOTE: At odds with the usual definition of the exchange energy density,
        (εₓ,ᵢⱼ(r) ∝ ρ(r)¹ᐟ³), XED contains an additional factor of D(r)
        (XED(r) ∝ D(r)⁴ᐟ³), since the exchange energy is calculated
        as K[D] = ∫ XED(r) dr rather than K[ρ] = ∫ ρ(r) εₓ(r) dr.

        :param msmd: The multistate matrix density in the electronic subspace
        :type msmd: :class:`~.MultistateMatrixDensity`

        :param coords: The Cartesian positions at which the kinetic energy
           density is calculated.
        :type coords: numpy.ndarray of shape (Ncoord,3)

        :return: XEDᵢⱼ(r), exchange energy density
        :rtype: numpy.ndarray of shape (2,Mstate,Mstate,Ncoord)
           XED[s,i,j,r] is the exchange energy density with spin s,
           between the electronic states i and j at position coords[r,:].
        """
        # number of grid points
        ncoord = coords.shape[0]
        # number of electronic states in the subspace
        nstate = msmd.number_of_states
        # up or down spin
        nspin = 2

        # exchange-energy density  XED[Dᵅ]ᵢⱼ(r) = 2¹ᐟ³ Cₓ [Dᵅ(r)⁴ᐟ³]ᵢⱼ
        XED = numpy.zeros((nspin,nstate,nstate,ncoord))

        # Evaluate D(r) on the integration grid.
        D, _, _ = msmd.evaluate(coords)

        # Trace over electronic states to get tr(D)(r).
        # `trace_D` has shape (2,Ncoord,), trace_D[s,:] = sum_i D[spin,i,i,:]
        trace_D = numpy.einsum('siir->sr', D)

        # Loop over spins. The exchange energy is computed separately for each spin
        # projection and added.
        for s in range(0, nspin):
            if numpy.all(trace_D[s,...] == 0.0):
                # There are no electrons with spin projection s
                # that could contribute to the exchange energy.
                continue

            # Cₓ from the "Gaussian" approximation in Eqn. (6.5.25) of [Parr&Yang]
            Cx = LSDAExchangeLikeFunctional.Cx_Gaussian
            prefactor = pow(2.0, 1.0/3.0) * Cx
            for r in range(0, ncoord):
                # Compute eigenvalues Λ and eigenvectors U of the symmetric matrix D.
                L, U = numpy.linalg.eigh(D[s,:,:,r])
                # Numerical rounding errors might produce tiny, negative eigenvalues instead of 0.
                assert numpy.all(L > -1.0e-12), "Eigenvalues of matrix density D are expected to be positive."

                # The fractional matrix power is obtained from the eigenvalue decomposition
                # as D⁴ᐟ³(r) = U(r) Λ⁴ᐟ³(r) Uᵀ(r)
                D_matrix_power = numpy.einsum('ia,a,ja->ij', U, pow(abs(L), 4.0/3.0), U)
                # LSDA exchange energy density
                exchange_energy_r = prefactor * D_matrix_power
                # Check that the exchange energy density is real.
                assert numpy.sum(abs(exchange_energy_r.imag)) < 1.0e-10

                XED[s,:,:,r] = exchange_energy_r

        return XED
