#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    import becke
except ImportError as err:
    print("""
    Solution of the Poisson equation requires the `becke` module
    which can be obtained from
       `https://github.com/humeniuka/becke_multicenter_integration`
    """)
    raise err

import numpy
import numpy.linalg as la

import pyscf.dft

from msdft.MultistateMatrixDensity import MultistateMatrixDensity

class HartreeLikeOperatorFunctional(object):
    def __init__(self, mol, level=8):
        """
        The Hartree energy is the interaction of a classical charge density with itself.
        There is no equivalent of the Hartree term in the multistate density functional
        formalism, because the Hartree part of the Coulomb energy does not correspond to
        an operator. We can define a functional of the matrix density D(r) that reduces
        to the Hartree energy in the case of a single electronic state, which is an
        analytical functional and transforms correctly under basis transformations U,
        i.e. `U⁻¹ J[D(r)] U = J[U⁻¹ D(r) U]` :

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫∫' Dᵢₖ(r) Dₖⱼ(r')/|r-r'|

        If there are multiple electronic state, the diagonals J[D(r)]ᵢᵢ differ from the
        classical Coulomb interaction of the state density of state i with itself, because
        the matrix product ∑ₖDᵢₖ(r) Dₖⱼ(r') mixes in transition densities to other
        states k≠i.

        :param mol: The molecule defines the integration grid.
        :type mol: pyscf.gto.Mole

        :param level: The level (3-8) controls the number of grid points
           in the integration grid.
        :type level: int
        """
        # generate a multicenter integration grid
        self.grids = pyscf.dft.gen_grid.Grids(mol)
        self.grids.level = level
        self.grids.build()

    def __call__(
            self,
            msmd : MultistateMatrixDensity):
        """
        compute the Hartree-like part of the electron-electron repulsion operator
        in the subspace of electronic states,

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫∫' Dᵢₖ(r) Dₖⱼ(r')/|r-r'|

        where Dᵢⱼ(r) is the electronic density of the state Ψᵢ, Dᵢᵢ(r) = ρᵢ(r),
        or the transition density between the states Ψᵢ and Ψⱼ, Dᵢⱼ(r).

        The 6-dimensional integral is calculated by solving the Poisson equation
        for the electrostatic potential generated by one of the (transition) densities,

          J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫ Dᵢₖ(r) Vₖⱼ(r)

        where

          ∇²Vₖⱼ(r) = -4π Dₖⱼ(r)

        is solved on a multicenter Becke grid.

        :param msmd: The multistate matrix density in the electronic subspace
        :type msmd: :class:`~.MultistateMatrixDensity`

        :return hartree_like_matrix: The Hartree-like matrix Jᵢⱼ in the subspace
           of the electronic states i,j=1,...,nstate
        :rtype hartree_like_matrix: numpy.ndarray of shape (nstate,nstate)
        """
        # number of grid points
        ncoord = self.grids.coords.shape[0]
        # number of electronic states in the subspace
        nstate = msmd.number_of_states

        # Evaluate D(r) on the integration grid.
        D, _, _ = msmd.evaluate(self.grids.coords)

        # For solving the Poisson equation another multicenter Becke grid
        # is employed, which can have a different number of angular and radial
        # grid points than the one for doing the integrals.

        # The multicenter grid is defined by the centers ...
        atomlist = []
        for nuclear_charge, nuclear_coords in zip(
                msmd.mol.atom_charges(), msmd.mol.atom_coords()):
            atomlist.append((int(nuclear_charge), nuclear_coords))
        # ... and the radial and angular grids.
        becke.settings.radial_grid_factor = 3
        becke.settings.lebedev_order = 23

        # [1] The Poisson equation is solved for each Dₖⱼ(r).
        V = numpy.zeros((nstate,nstate,ncoord))
        for k in range(0, nstate):
            for j in range(0, nstate):
                # A function for evaluating the (transition) density Dₖⱼ(r) on
                # the multicenter Becke grid.
                def density_function(x, y, z):
                    # The `becke` module and the `msdft` module use different
                    # shapes for the coordinates of the grid points. Before
                    # passing the grid to `msdft`, the arrays have to be flattened
                    # and reshaped as (ncoord,3). Before returning the density,
                    # it has to be brought into the same shape as each input coordinate
                    # array.
                    coords = numpy.vstack(
                        [x.flatten(), y.flatten(), z.flatten()]).transpose()

                    # Evaluate the density.
                    spin_density, _, _ = msmd.evaluate(coords)
                    # The Coulomb potential does not distinguish spins, so
                    # sum over spins.
                    density = spin_density[0,k,j,:]+ spin_density[1,k,j,:]

                    # Give it the same shape as the input arrays.
                    density = numpy.reshape(density, x.shape)
                    return density

                # The solution of the Poisson equation
                #  ∇²potential(r) = -4π density(r)
                # is returned as a callable.
                potential_function = becke.poisson(atomlist, density_function)

                # The electrostatic potential is evaluated on the same
                # integration grid as the density.
                V[k,j,:] = potential_function(
                    # x
                    self.grids.coords[:,0],
                    # y
                    self.grids.coords[:,1],
                    # z
                    self.grids.coords[:,2])

        # [2] Integrate and do the matrix-matrix product.
        #
        #  J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫ Dᵢₖ(r) Vₖⱼ(r)
        #
        hartree_like_matrix = 0.5 * numpy.einsum(
            'r,ikr,kjr->ij',
            self.grids.weights,
            # Both spins feel the same Coulomb potentials, so sum over spins.
            D[0,...]+D[1,...],
            V)

        return hartree_like_matrix
