name: Unit tests for msdft package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout dependencies
        uses: actions/checkout@v3
        with:
          repository: humeniuka/becke_multicenter_integration
      - name: Install dependencies
        working-directory: ./becke
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Checkout package
        uses: actions/checkout@v3
      - name: Install package
        run: |
          pip install -e .

      - name: Test MultistateMatrixDensity class
        working-directory: tests
        run: |
          python test_MultistateMatrixDensity.py
      - name: Test KineticOperatorFunctional class
        working-directory: tests
        run: |
          python test_KineticOperatorFunctional.py
      - name: Test NuclearPotentialOperator class
        working-directory: tests
        run: |
          python test_NuclearPotentialOperator.py
      - name: Test HartreeLikeOperatorFunctional class
        working-directory: tests
        run: |
          python test_ElectronRepulsionOperators.py
